-- Add Gamification Fields
ALTER TABLE users ADD COLUMN level INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN current_xp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN target_xp INTEGER NOT NULL DEFAULT 100;
ALTER TABLE users ADD COLUMN current_streak INTEGER NOT NULL DEFAULT 0;

-- Add Bio Fields
ALTER TABLE users ADD COLUMN birth_date DATE;
ALTER TABLE users ADD COLUMN weight DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN height DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN body_fat_percentage DOUBLE PRECISION;

-- Enums (stored as String in JPA)
ALTER TABLE users ADD COLUMN gender VARCHAR(50);
ALTER TABLE users ADD COLUMN activity_level VARCHAR(50);
ALTER TABLE users ADD COLUMN goal VARCHAR(50);
